name: CI - Flask DevOps App

on:
  push:
    branches: [ "dev", "main" ]
  pull_request:
    branches: [ "dev", "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flask

      - name: Run simple test
        run: |
          echo "Running Flask test..."
          python -c "import flask; print('✅ Flask imported successfully!')"

      - name: Build success
        run: echo "🎉 Build and test completed successfully!"
